export enum InstitutionType {
  PublicSchool = 'PublicSchool',
  PrivateSchool = 'PrivateSchool',
  CharterSchool = 'CharterSchool',
  InternationalSchool = 'InternationalSchool',
  PublicUniversity = 'PublicUniversity',
  PrivateUniversity = 'PrivateUniversity',
  CommunityCollege = 'CommunityCollege',
  TechnicalCollege = 'TechnicalCollege',
  LiberalArtsCollege = 'LiberalArtsCollege',
  PrimarySchool = 'PrimarySchool',
  SecondarySchool = 'SecondarySchool',
  HighSchool = 'HighSchool',
  VocationalSchool = 'VocationalSchool',
  SpecialEducationSchool = 'SpecialEducationSchool',
  LanguageSchool = 'LanguageSchool',
  Other = 'Other',
}
